
/*  Function IB_XP_CALC_ADD_VARIABLE  */
DECLARE EXTERNAL FUNCTION IB_XP_CALC_ADD_VARIABLE
   INTEGER, VARCHAR(2048)
   RETURNS INTEGER BY VALUE
  ENTRY_POINT "ib_AddCalculatorVariable"  MODULE_NAME "D:\USER\GRANIT\SRC\CALCF\CALCF.DLL"
---

/*  Function IB_XP_CALC_CLEAR_VARIABLES  */
DECLARE EXTERNAL FUNCTION IB_XP_CALC_CLEAR_VARIABLES
   INTEGER
   RETURNS INTEGER BY VALUE
  ENTRY_POINT "ib_CalcClearVariables"  MODULE_NAME "D:\USER\GRANIT\SRC\CALCF\CALCF.DLL"
---

/*  Function IB_XP_CALC_CREATE  */
DECLARE EXTERNAL FUNCTION IB_XP_CALC_CREATE
    RETURNS INTEGER BY VALUE
  ENTRY_POINT "ib_AllocCalculator"  MODULE_NAME "D:\USER\GRANIT\SRC\CALCF\CALCF.DLL"
---

/*  Function IB_XP_CALC_ERROR  */
DECLARE EXTERNAL FUNCTION IB_XP_CALC_ERROR
   INTEGER
   RETURNS INTEGER BY VALUE
  ENTRY_POINT "ib_CalcGetError"  MODULE_NAME "D:\USER\GRANIT\SRC\CALCF\CALCF.DLL"
---

/*  Function IB_XP_CALC_FORMULA  */
DECLARE EXTERNAL FUNCTION IB_XP_CALC_FORMULA
   INTEGER, VARCHAR(2048)
   RETURNS DOUBLE PRECISION BY VALUE
  ENTRY_POINT "ib_CalcFormula"  MODULE_NAME "D:\USER\GRANIT\SRC\CALCF\CALCF.DLL"
---

/*  Function IB_XP_CALC_FREE  */
DECLARE EXTERNAL FUNCTION IB_XP_CALC_FREE
   INTEGER
   RETURNS INTEGER BY VALUE
  ENTRY_POINT "ib_FreeCalculator"  MODULE_NAME "D:\USER\GRANIT\SRC\CALCF\CALCF.DLL"