#include <kertl.hpp>

namespace KeRTL
{

    bool __fastcall TMultiRdSingleWr::ReadLock   (DWORD to )
    {
     bool ret(false);
     return ret;
    }

    bool __fastcall TMultiRdSingleWr::ReadUnlock ()
    {
     bool ret(false);
     return ret;
    }

    bool __fastcall TMultiRdSingleWr::WriteLock  (DWORD to )
    {
     bool ret(false);
     return ret;
    }

    bool __fastcall TMultiRdSingleWr::WriteUnlock()
    {
     bool ret(false);
     return ret;
    }

}

 
