rem clear temporary files

cd cpc152dev
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd cpc152devwnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd gkipmodem
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd gkipmodem_wnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd gklib
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd tlm_painter
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd vcl
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd gksecurity
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd gkuser_tools
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd gktlm_viewer
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd gktlm_viewer_wnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd gktlmdb
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd gktlmdbwnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd granit_tcpio
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd granitmdm
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd granitmdm_wnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd handle
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
del *.#*
cd ..

cd kernel
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd kexplorer
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd mediumdb
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd mediumdbwnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..
cd ..

cd modbusmdm
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd modbusmdmwnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd ..

cd modemmer
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd modemmerwnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd ..

cd otdhlpr
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd rechistory
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd rechistory_wnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd ..

cd reporterex
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd reporterex_wnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd ..

cd scale
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd scale_wnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd ..

cd tlmobj_painter
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd tlmobj_std_painter
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd vtdcnt
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*

cd vtdcntwnd
cd __history
del /Q *.*
cd ..
del *.bak
del *.~*
cd ..

cd ..
